// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATWPCBB32U9IukSzY8xAwetmJYT1oMrIs',
    appId: '1:652322531717:web:d495bd1c68667c80febcec',
    messagingSenderId: '652322531717',
    projectId: 'vetcure-chat',
    authDomain: 'vetcure-chat.firebaseapp.com',
    storageBucket: 'vetcure-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKPV_r5QWacWdNNIOApcY--A-mDPg99bQ',
    appId: '1:652322531717:android:43e0ea25e4a70532febcec',
    messagingSenderId: '652322531717',
    projectId: 'vetcure-chat',
    storageBucket: 'vetcure-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeScB_hetT-V5jvYcRiZqxGtHr_WtS2AI',
    appId: '1:652322531717:ios:c4a813e6a14dcbe2febcec',
    messagingSenderId: '652322531717',
    projectId: 'vetcure-chat',
    storageBucket: 'vetcure-chat.appspot.com',
    iosClientId: '652322531717-msi886077922e68uidvkq0s9m4g73f54.apps.googleusercontent.com',
    iosBundleId: 'com.example.vetcurekartchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeScB_hetT-V5jvYcRiZqxGtHr_WtS2AI',
    appId: '1:652322531717:ios:c4a813e6a14dcbe2febcec',
    messagingSenderId: '652322531717',
    projectId: 'vetcure-chat',
    storageBucket: 'vetcure-chat.appspot.com',
    iosClientId: '652322531717-msi886077922e68uidvkq0s9m4g73f54.apps.googleusercontent.com',
    iosBundleId: 'com.example.vetcurekartchat',
  );
}
